
services:
  user:
    build: ./server/user
    container_name: userapp_container
    ports:
      - 8000:8000

    volumes:
      - ./server/user:/app

  schedule:
    build: ./server/schedule
    container_name: scheduleapp_container
    ports:
      - 8001:8001

    volumes:
      - ./server/schedule:/app

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq_container
    ports:
      - 15672:15672

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports: 
      - 8080:8080
    volumes:
      - ./html:/usr/share/nginx/html

    