
services:
  user:
    build: ./server/user
    container_name: userapp
    ports:
      - 8000:8000

    volumes:
      - ./server/user:/app

  schedule:
    build: ./server/schedule
    container_name: scheduleapp
    ports:
      - 8080:8080

    volumes:
      - ./server/schedule:/app

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672

    