
services:
  user:
    build: ./server/user
    container_name: userapp
    ports:
      - 8000:8000

    volumes:
      - ./server/user:/app

  schedule:
    build: ./server/schedule
    container_name: scheduleapp
    ports:
      - 8080:8080

    volumes:
      - ./server/schedule:/app

